# Project-wide Gradle settings
# Reduce memory and disable daemon for Docker CI stability
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx1024m -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Android
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official
